### ISSUE TITLE
Add a "via" parameter for Twitter shares

### ISSUE THREAD

**Issue by goodguyry** [Story-Worldwide/story-share#6]
According to the [Twitter share documentation](https://dev.twitter.com/web/tweet-button#component-via), there is an optional parameter for tweet attribution ("via @username").

Please add a check for a `data-via` attribute on all elements with `data-type="twitter"` and incorporate the attribute's value into the "via" parameter.

**Comment by matgargano** [comment]
covered in 0.1.1
