### ISSUE TITLE
`relativeMediaUrls: true` should default to the current page's directory

### ISSUE THREAD

**Issue by goodguyry** [Story-Worldwide/story-share#7]
With the default `relativeMediaUrls` value being `true`, given `data-media="some-image.jpg"` on a page at http://example.com/some-dir/, storyShare will pick the image up from `http://example.com/some-dir/some-image.jpg`.

The problem arises when the page is at `http://example.com/some-dir/filename.html`. In this scenario, storyShare expects the image to be located at `http://example.com/some-dir/filename.htmlsome-image.jpg`.

Maybe check for a trailing slash or '.' and remove the filename?

```javascript
var url = window.location.href,
    end = url.split('/').pop();

if (end.search(/\./) > -1 || end.slice(-1) !== '/') {
    url = url.substring(0, url.length - (end.length));
}
```

Just a thought. There may be issues and edge cases with this approach that I'm not thinking about right now.

**Comment by matgargano** [comment]
appears to be covered in 34cb6b3fb423699075df112139c5187e506d1242
